# Railway deployment configuration
# This file configures deployment settings for Railway platform

[build]
buildCommand = "dotnet restore src/WikipediaMcpServer/WikipediaMcpServer.csproj && dotnet publish src/WikipediaMcpServer/WikipediaMcpServer.csproj -c Release -o ./publish"

[deploy]
startCommand = "dotnet ./publish/WikipediaMcpServer.dll"
healthcheckPath = "/api/wikipedia/health"
healthcheckTimeout = 30

[settings]
# Automatically restart on failure
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3