services:
  - type: web
    name: wikipedia-mcp-server
    runtime: docker
    plan: free  # Change to 'starter' or higher for production
    region: oregon  # Available regions: oregon, frankfurt, singapore
    buildCommand: |
      dotnet restore src/WikipediaMcpServer/WikipediaMcpServer.csproj
      dotnet publish src/WikipediaMcpServer/WikipediaMcpServer.csproj -c Release -o ./publish --no-restore
    startCommand: dotnet ./publish/WikipediaMcpServer.dll
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: DOTNET_ENVIRONMENT
        value: Production
      - key: MCP_MODE
        value: "false"  # Set to "true" for MCP-only mode
      - key: ASPNETCORE_HTTPS_PORT
        value: ""  # Disable HTTPS port configuration
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: "true"  # Enable forwarded headers for reverse proxy
    # Auto-deploy from GitHub
    autoDeploy: true
    # Custom domains (optional)
    # domains:
    #   - your-custom-domain.com